//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterAPI_Project.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationMethodPermission
    {
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public int MethodId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Method Method { get; set; }
    }
}
