//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterAPI_Project.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APIDashboardEntities : DbContext
    {
        public APIDashboardEntities()
            : base("name=APIDashboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<MethodLog> MethodLogs { get; set; }
        public virtual DbSet<ApplicationMethodPermission> ApplicationMethodPermissions { get; set; }
        public virtual DbSet<Method> Methods { get; set; }
    }
}
