//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterAPI_Project.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MethodLog
    {
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public System.DateTime RequestTime { get; set; }
        public System.DateTime ResponseTime { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
        public string MethodName { get; set; }
        public int HttpStatus { get; set; }
    }
}
